CREDENTIALS_FILE = "conf/local/credentials.yml"
DATASET_ID = "4ijn-s7e5"
BUCKET = "data-product-architecture-equipo-2"
INGESTA_INICIAL_PATH = "ingestion/initial/historic-inspections"
INGESTA_CONSECUTIVA_PATH = "ingestion/consecutive/consecutive-inspections"
LIMPIEZA_PATH = "clean/inspections"
FEATURE_ENGINEERING_PATH = "feature-engineering/inspections"