CREATE SCHEMA IF NOT EXISTS api;

DROP TABLE IF EXISTS api.scores;

CREATE TABLE IF NOT EXISTS api.scores (
	id SERIAL PRIMARY KEY,
	inspection_id INTEGER NOT NULL,
	name VARCHAR(255) NOT NULL,
	risk VARCHAR(255) NOT NULL,
	address VARCHAR(512) NOT NULL,
	zip_code INTEGER NOT NULL, 
	inspection_date TIMESTAMP NOT NULL,
	predicted_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	predicted CHAR(4) NOT NULL
);

CREATE SCHEMA IF NOT EXISTS monitor;

DROP TABLE IF EXISTS monitor.scores;

CREATE TABLE IF NOT EXISTS monitor.scores (
	id SERIAL PRIMARY KEY,
	inspection_id INTEGER NOT NULL,
	name VARCHAR(255) NOT NULL,
	risk VARCHAR(255) NOT NULL,
	address VARCHAR(512) NOT NULL,
	zip_code INTEGER NOT NULL, 
	inspection_date TIMESTAMP NOT NULL,
	predicted_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	predicted CHAR(4) NOT NULL
);